name: Publish AsefileSharp.Unity

on:
  push:
    branches:
      - stable
    paths:
      - 'src/AsefileSharp.Unity/**/*.cs'
      - 'src/AsefileSharp.Unity/*.csproj'
  pull_request:
    types: [closed]
    branches:
      - stable
    paths:
      - 'src/AsefileSharp.Unity/**/*.cs'
      - 'src/AsefileSharp.Unity/*.csproj'
env:  
  APP_NAME: AsefileSharp.Unity                             # set this to your application's name
  NETCORE_VERSION: '3.1.200'                                 # set this to the .NET Core version to use
  GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}    # set this to access token to github.com
  GITHUB_API_KEY: ${{ github.token }}                        # set this to access token to github.com

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Update NuGet package
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Setup .NET Core ${{ env.NETCORE_VERSION }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.NETCORE_VERSION }}
      - name: Build solution and generate NuGet package
        working-directory: ./src/${{ env.APP_NAME }}
        run: dotnet pack -c Release -o out
      - name: Add NuGet sources
        working-directory: ./src/${{ env.APP_NAME }}
        run: dotnet nuget add source https://nuget.pkg.github.com/${{ env.GITHUB_REPOSITORY_OWNER }}/index.json --name github
      - name: Push generated packages to GitHub registry
        working-directory: ./src/${{ env.APP_NAME }}
        run: dotnet nuget push ./out/*.nupkg --source github --api-key ${{ env.GITHUB_API_KEY }} --skip-duplicate --no-symbols true
      - name: Upload NuGet package
        working-directory: ./src/${{ env.APP_NAME }}
        uses: actions/upload-artifact@v2.2.1
        with:
          name: ${{ env.APP_NAME }}
          path: "**/*.nupkg"